CustomPage/CustomPage/Models/Coffee.cs
using System.ComponentModel.DataAnnotations;
using CustomPage.Repositories.Contacts.Commons;

namespace CustomPage.Models
{
    public class Coffee: IEntity
    {
        public long Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
    }
}

CustomPage/CustomPage/Models/Contact.cs
using System.ComponentModel.DataAnnotations;
using CustomPage.App_LocalResources;
using CustomPage.Repositories.Contacts.Commons;

namespace CustomPage.Models
{
    public class Contact: IEntity
    {
        public long Id { get; set; }
        
        [Display(Name = "contact_name_attr", ResourceType = typeof(GlobalRes))]
        [Required(ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_name_error")]
        [MaxLength(50, ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_name_error_length")]
        public string Name { get; set; }

        [Display(Name = "contact_lastname_attr", ResourceType = typeof(GlobalRes))]
        [Required (ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_lastname_error")]
        [MaxLength(50, ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_name_error_length")]
        public string Lastname { get; set; }

        [Display(Name = "contact_email_attr", ResourceType = typeof(GlobalRes))]
        [Required(ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_email_error")]
        [EmailAddress(ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_email_error_type")]
        public string Email { get; set; }

        [Display(Name = "contact_comment_attr", ResourceType = typeof(GlobalRes))]
        [Required (ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_comment_error")]
        [MaxLength(400, ErrorMessageResourceType = typeof(GlobalRes), ErrorMessageResourceName = "contact_form_name_error_length")]
        public string Comment { get; set; }
    }
}

CustomPage/CustomPage/Controllers/AboutUsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using CustomPage.Factories;
using CustomPage.Filters;
using CustomPage.Models;
using CustomPage.Repositories;

namespace CustomPage.Controllers
{
    [Localization("en")]
    public class AboutUsController : Controller
    {
        public ActionResult WhereAre()
        {
            return PartialView("WhereAre");
        }
        public ActionResult ContactUs()
        {
            return PartialView("ContactUs");
        }
        public ActionResult Specializations()
        {
            CoffeeRepository oCoffeeRepository = new CoffeeRepository(SqlEngineSpecificationsFactory.CreateSqlEngineSpecifications());
            var coffeeList = oCoffeeRepository.GetAll();
            return PartialView("Specializations", coffeeList);
        }
        public ActionResult HowWeAre()
        {
            return PartialView("WhoWeAre");
        }

        [HttpPost]
        public JsonResult addContact(Contact oContact)
        {
            if (ModelState.IsValid)
            {
                ContactRepository oContactRepository = new ContactRepository(SqlEngineSpecificationsFactory.CreateSqlEngineSpecifications());
                oContactRepository.Create(oContact);
                return Json(new { response = true });
            }

            return Json(new { response = false });
        }
    }
}

CustomPage/CustomPage/Controllers/HomeController.cs
using System.Web.Mvc;
using CustomPage.Filters;

namespace CustomPage.Controllers
{
    [Localization("en")]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

CustomPage/CustomPage/Views/AboutUs/ContactUs.cshtml
@using CustomPage.App_LocalResources
@model CustomPage.Models.Contact

<div class="content contact">
    <div class="text-center contact-container mt40 pt40 pb40" style="height: 100vh;">
        <h2 class="text-center brown underlined pb40">@GlobalRes.about_contact_us_title</h2>
        <div class="information">
            <h2 class="mb20">@GlobalRes.about_contact_us_phone</h2>
            <div class="mb20">
                <p class="mb5">@(GlobalRes.about_contact_us_phone_USA): +1 111 9211111 </p>
                <p>@(GlobalRes.about_contact_us_phone_AR): +54 0223 1111111</p>
            </div>
            <h2 class="mb20">@GlobalRes.about_contact_us_email</h2>
            <div class="mb5">
                <a href="mailto:hello@test.net">hello@test.net</a>
            </div>
            <h2 class="mb20">@GlobalRes.about_contact_us_address</h2>
            <div class="mb10">
                <p>Mar Del Plata, Argentina</p>
            </div>

            <div class="contact-form mb10">
                <h2 class="mt20 mb20">@GlobalRes.about_contact_us_comment_title</h2>
                @using (Html.BeginForm("addContact", "AboutUs", FormMethod.Post, new { @id = "registerContact" }))
            {
                <ol>
                    <li class="mb10">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name)
                        @Html.ValidationMessageFor(m => m.Name)
                    </li>
                    <li class="mb10">
                        @Html.LabelFor(m => m.Lastname)
                        @Html.TextBoxFor(m => m.Lastname)
                        @Html.ValidationMessageFor(m => m.Lastname)
                    </li>
                    <li class="mb10">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email)
                        @Html.ValidationMessageFor(m => m.Email)
                    </li>
                    <li class="mb10">
                        @Html.LabelFor(m => m.Comment)
                        @Html.TextBoxFor(m => m.Comment)
                        @Html.ValidationMessageFor(m => m.Comment)
                    </li>
                </ol>
                <div class="row">
                    <input class="btn btn-default" type="submit" value="@GlobalRes.contact_form_btn_submit" id="btnSubmit" />
                </div>
                <div class="row mt10">
                    <span id="success-message" class="success-message">@GlobalRes.success_message</span>
                    </div>
                }
                </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

        $("#btnSubmit").click(function (e) {
            e.preventDefault();
            var _this = $(this);
            var _form = _this.closest("form");

            $(this).removeData("validator").removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse($(this));

            $(_form).removeData("validator").removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse($(_form));

            _form.validate();
            if (_form.valid()) {
                $.post(_form.attr("action"), _form.serialize(), function (data) {
                    if (data.response === true) {
                        $("#Name").val("");
                        $("#Lastname").val("");
                        $("#Email").val("");
                        $("#Comment").val("");
                        $('#success-message').fadeIn().delay(2000).fadeOut('slow');
                    }
                });
            }
        });
    });
</script>

CustomPage/CustomPage/Views/AboutUs/Specializations.cshtml
@using CustomPage.App_LocalResources
@using CustomPage.Models

<div class="content speciality">
    <h2 class="mt40 pt40 text-center">@GlobalRes.about_specializations_title</h2>
    <div class="row center-margin">

        @{
            int index = 1;
        }

        @foreach (var item in Model)
        {
            if (index % 2 == 0)
            {
                <div class="pair">
                    <div class="display-inline text-center">
                        <img src="../../Images/coffeRecipe/@(item.Id).jpg" />
                    </div>
                    <div class="display-inline text-center pl30 pr30 content-text">
                        <h2 class="mb10"></h2>
                        <p>@item.Description</p>
                    </div>
                </div>
            }
            else
            {
                <div class="odd">
                    <div class="display-inline text-center pl30 pr30 content-text">
                        <h2 class="mb10"></h2>
                        <p>@item.Description</p>
                    </div>
                    <div class="display-inline text-center">
                        <img src="../../Images/coffeRecipe/@(item.Id).jpg"/>
                    </div>
                </div>
            }
            ++index;
        }
    </div>
</div>

CustomPage/CustomPage/Views/AboutUs/WhereAre.cshtml
@using CustomPage.App_LocalResources

<div class="content who">
    <div class="text-container odd" style="height: 100vh;">
        <h2 class="mt40 pt40 text-center">@GlobalRes.about_where_are_we</h2>
    <div style="margin-top: 20px;">
        @GlobalRes.about_where_are_we_content
    </div>
    <img style="margin-top: 45px; margin-bottom: 40px; max-width: 50%; width: 60%; left: 25%;" src="../../Images/wherearewe/location2.jpg" />
</div>
</div>

CustomPage/CustomPage/Views/AboutUs/WhoWeAre.cshtml
@using CustomPage.App_LocalResources

<div class="content who" >
    <div class="text-container odd" style="height: fit-content">
        <h2 class="mt40 pt40 text-center">@GlobalRes.about_who_we_are</h2>
        <div style="margin-top: 20px;">
            @GlobalRes.about_who_we_are_intro
        </div>
        <img style="margin-top: 45px; margin-bottom: 40px; max-width: 60%; width: 90%; left: 20%;" src="../../Images/whoweare/Quality-Banner.jpg" />
        <div style="margin-top: 20px; margin-bottom:30px;">
            @GlobalRes.about_who_we_are_content
        </div>
    </div>
</div>

CustomPage/CustomPage/Views/Home/About.cshtml
@using CustomPage.App_LocalResources

<div class="content">
    <div class="about-container">
        <div class="row button-container">
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3 text-center">
                @Ajax.ActionLink(GlobalRes.about_who_we_are, "HowWeAre", "AboutUs", new AjaxOptions { UpdateTargetId = "content-loader" })
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3 text-center">
                @Ajax.ActionLink(GlobalRes.about_specializations, "Specializations", "AboutUs", new AjaxOptions { UpdateTargetId = "content-loader" })
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3 text-center">
                @Ajax.ActionLink(GlobalRes.about_where_are_we, "WhereAre", "AboutUs", new AjaxOptions { UpdateTargetId = "content-loader" })
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3 text-center">
                @Ajax.ActionLink(GlobalRes.about_contact_us, "ContactUs", "AboutUs", new AjaxOptions { UpdateTargetId = "content-loader" })
            </div>
        </div>
        <div id="content-loader">
            @Html.Partial("~/Views/AboutUs/WhoWeAre.cshtml")
        </div>
    </div>
</div>

CustomPage/CustomPage/Views/Home/Index.cshtml
<div class="content">
    <div class="home-container">
        <div class="title">
            <h2 class="text-center">Amazing Coffee!</h2>
        </div>
        <div class="cafe">
            <div class="slick-coffe">
                <div>
                    <img src="../../Images/slick/i-love-heart-coffee-wallpapers.jpg" alt="i-love-heart" />
                </div>
                <div>
                    <img src="../../Images/slick/happy-face.jpg" alt="happy-face" />
                </div>
                <div>
                    <img src="../../Images/slick/i-love-heart-coffee-wallpapers.jpg" alt="i-love-heart" />
                </div>
                <div>
                    <img src="../../Images/slick/happy-face.jpg" alt="happy-face"/>
                </div>
                <div>
                    <img src="../../Images/slick/i-love-heart-coffee-wallpapers.jpg" alt="i-love-heart" />
                </div>
                <div>
                    <img src="../../Images/slick/happy-face.jpg" alt="happy-face"/>
                </div>
                <div>
                    <img src="../../Images/slick/i-love-heart-coffee-wallpapers.jpg" alt="i-love-heart" />
                </div>
                <div>
                    <img src="../../Images/slick/happy-face.jpg" alt="happy-face" />
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
       
            $('.slick-coffe').slick({
                dots: true,
                centerMode: true,
                centerPadding: '60px',
                slidesToShow: 3,
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 2000,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            centerMode: true,
                            centerPadding: '40px',
                            slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            centerMode: true,
                            centerPadding: '40px',
                            slidesToShow: 1
                        }
                    }
                ]
            });
       
    });
   
</script>

CustomPage/CustomPage/Views/Shared/_Layout.cshtml
@using CustomPage.App_LocalResources

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="../../Style/css/main.css" rel="stylesheet"/>
    <script src="../../Assets/js/jQuery3.1.1/jquery-3.1.1.min.js"></script>
    <script src="../../Assets/js/slick/slick.min.js"></script>
    <script src="../../Scripts/jquery.validate.js"></script>
    <script src="../../Scripts/jquery.validate.unobtrusive.js"></script>
    <link href="../../Assets/js/slick/slick.css" rel="stylesheet"/>
    <link href="../../Assets/js/slick/slick-theme.css" rel="stylesheet"/>
    <script src="../../Scripts/jquery-ajax-unobtrusive.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Coffee - Custom Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav main-nav">
                    <li>@Html.ActionLink(GlobalRes.nav_Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(GlobalRes.nav_AboutUs, "About", "Home")</li>
                    <li style="float: right;"><a href="/en">@GlobalRes.lang_eng</a></li>
                    <li style="float: right;"><a href="/es">@GlobalRes.lang_es</a></li>
                    <li style="float: right;"><img src="../../Images/app/icons8-geography-filled-30.png" style="margin-top: 10px;"></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" id="main-container">
        @RenderBody()
        <hr />
        <footer>
                <span>&copy; @DateTime.Now.Year - Coffee Custom Page</span>
       </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>